#!/bin/bash

# Usage: /sbin/slapd-restore dbnum file
dbnum=$1
file=$2

backupPath="/data/backup"
file="$backupPath/$file"

# stop slapd
sv stop /container/run/process/slapd

TEMP_FILE=$(mktemp)

if [ "$LDAP_ENCRYPT_BACKUP" == "true" ] && [ -f "$LDAP_ENCRYPT_SYMKEY_FILE" ]; then
    TEMP_FILE_RESTORE=$(mktemp) 
    openssl enc -d -aes-256-cbc -pbkdf2 -pass file:"$LDAP_ENCRYPT_SYMKEY_FILE" -in $file -out $TEMP_FILE_RESTORE
  	gunzip -c $TEMP_FILE_RESTORE > $TEMP_FILE

  	rm $TEMP_FILE_RESTORE

  # to decrypt, use something like:
  # openssl enc -d -aes-256-cbc -pbkdf2 -in mydatabase-2021-02-22_15-00-45.sql.gz.e -out mydatabase.sql.gz -pass file:/run/secrets/enc_backup_symkey.key
  # then, recover the database using the mydatabase.sql.gz as usual
else
  gunzip -c $file > $TEMP_FILE  
fi

chown openldap:openldap $TEMP_FILE

/sbin/setuser openldap slapadd -c -F /etc/ldap/slapd.d -n $dbnum -l $TEMP_FILE

# restart slapd
sv start /container/run/process/slapd

rm $TEMP_FILE

exit 0
