#!/bin/bash -e

# Usage: /sbin/slapd-backup dbnum filename
dbnum=$1
filename=$2

backupPath="/data/backup"

source /container/run/environment.sh

# delete backups that are over $LDAP_BACKUP_TTL days
#this line was stripped out from original image

# Date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"


if [ "$LDAP_ENCRYPT_BACKUP" == "true" ] && [ -f "$LDAP_ENCRYPT_SYMKEY_FILE" ]; then
  backupFilePath="$backupPath/$(date "$dateFileFormat")-$filename.gz.e"
  /usr/sbin/slapcat -F /etc/ldap/slapd.d -n $dbnum | gzip | \
    openssl enc -e -aes-256-cbc -salt -pbkdf2 \
      -pass file:"$LDAP_ENCRYPT_SYMKEY_FILE" \
      -out "${backupFilePath}"
  # to decrypt, use something like:
  # openssl enc -d -aes-256-cbc -pbkdf2 -in mydatabase-2021-02-22_15-00-45.sql.gz.e -out mydatabase.sql.gz -pass file:/run/secrets/enc_backup_symkey.key
  # then, recover the database using the mydatabase.sql.gz as usual
else
  backupFilePath="$backupPath/$(date "$dateFileFormat")-$filename.gz"
  /usr/sbin/slapcat -F /etc/ldap/slapd.d -n $dbnum | gzip > $backupFilePath
fi
chmod 600 $backupFilePath

if [[ "$UPLOAD_TO_S3" == "true" ]]; then
  # Upload backup to S3. The backupFilePath is the config backup file path
  echo "Upload stripped out from original image"
  echo "Upload successful"
fi

exit 0