#!/bin/bash -e

# Usage: /sbin/slapd-backup dbnum filename
dbnum=$1
filename=$2

backupPath="/data/backup"

source /container/run/environment.sh

# Date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"

if [ "$LDAP_ENCRYPT_BACKUP" == "true" ] && [ -f "$LDAP_ENCRYPT_SYMKEY_FILE" ]; then
  backupFilePath="$backupPath/$(date "$dateFileFormat")-$filename.gz.e"
  /usr/sbin/slapcat -F /etc/ldap/slapd.d -n $dbnum | gzip | \
    openssl enc -e -aes-256-cbc -salt -pbkdf2 \
      -pass file:"$LDAP_ENCRYPT_SYMKEY_FILE" \
      -out "${backupFilePath}"
else
  backupFilePath="$backupPath/$(date "$dateFileFormat")-$filename.gz"
  /usr/sbin/slapcat -F /etc/ldap/slapd.d -n $dbnum | gzip > $backupFilePath
fi
chmod 600 $backupFilePath

exit 0