version: '3.2'
services:
  openldap:
    image: bcv-openldap:1.4.0-r1
    container_name: openldap
    ports:
      - 389:389
      - 636:636
    hostname: openldap
    environment:
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "chain.pem"
      LDAP_ORGANISATION: "TEST"
      LDAP_DOMAIN: "test"
      LDAP_BASE_DN: "dc=test"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "never"
#      LDAP_RFC2307BIS_SCHEMA: "true"
#      LDAP_READONLY_USER: "true"
#      LDAP_READONLY_USER_USERNAME: "readonly"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/ldap
        read_only: false
      - type: bind
        source: ./config
        target: /etc/ldap/slapd.d
        read_only: false
      - type: bind
        source: ./secrets/certs
        target: /container/service/slapd/assets/certs/
        read_only: false
      - type: bind
        source: ./backup
        target: /data/backup
        read_only: false
      - type: bind
        source: ./secrets/pwfiles
        target: /container/environment/90-adminpw
        read_only: true
